seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 50000
empirical_normalization: false
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.005
  desired_kl: 0.01
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  symmetry_cfg: null
  rnd_cfg: null
clip_actions: null
save_interval: 100
experiment_name: g1_homie
run_name: ''
logger: tensorboard
neptune_project: leggedlab
wandb_project: g1_homie
resume: true
load_run: 2025-08-27_11-20-31
load_checkpoint: model_.*.pt
